//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAnalyzer.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodeAnalyzerContainer : DbContext
    {
        public CodeAnalyzerContainer()
            : base("name=CodeAnalyzerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LanguageDeclaration> LanguageDeclaration { get; set; }
        public virtual DbSet<CategoryDeclaration> CategoryDeclaration { get; set; }
        public virtual DbSet<RuleDeclaration> RuleDeclaration { get; set; }
        public virtual DbSet<CategoryDefinition> CategoryDefinition { get; set; }
        public virtual DbSet<ProjectDefinition> ProjectDefinition { get; set; }
        public virtual DbSet<RuleDefinition> RuleDefinition { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<Directory> Directory { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<Batch> Batch { get; set; }
        public virtual DbSet<ExcludedDirectory> ExcludedDirectory { get; set; }
        public virtual DbSet<ExcludedFile> ExcludedFile { get; set; }
    }
}
