//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAnalyzer.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public System.Guid Id { get; set; }
        public int LineNumber { get; set; }
        public string CodeExtract { get; set; }
        public string RootDirectoryPath { get; set; }
        public string Filename { get; set; }
        public int Status { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual RuleDeclaration RuleDeclaration { get; set; }
        public virtual ProjectDefinition ProjectDefinition { get; set; }
        public virtual RuleDefinition RuleDefinition { get; set; }
        public virtual CategoryDefinition CategoryDefinition { get; set; }
    }
}
