//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAnalyzer.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDefinition
    {
        public ProjectDefinition()
        {
            this.CategoryDefinitions = new HashSet<CategoryDefinition>();
            this.Directories = new HashSet<Directory>();
            this.ExcludedDirectories = new HashSet<ExcludedDirectory>();
            this.Files = new HashSet<File>();
            this.ExcludedFiles = new HashSet<ExcludedFile>();
            this.Match = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public bool Enabled { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CategoryDefinition> CategoryDefinitions { get; set; }
        public virtual ICollection<Directory> Directories { get; set; }
        public virtual ICollection<ExcludedDirectory> ExcludedDirectories { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<ExcludedFile> ExcludedFiles { get; set; }
        public virtual User Owner { get; set; }
        public virtual User Contributers { get; set; }
        public virtual User Followers { get; set; }
        public virtual ICollection<Match> Match { get; set; }
    }
}
