//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAnalyzer.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleDeclaration
    {
        public RuleDeclaration()
        {
            this.LanguageDeclaration = new HashSet<LanguageDeclaration>();
            this.RuleDefinition = new HashSet<RuleDefinition>();
            this.Match = new HashSet<Match>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Severity { get; set; }
        public string Expression { get; set; }
    
        public virtual CategoryDeclaration CategoryDeclaration { get; set; }
        public virtual ICollection<LanguageDeclaration> LanguageDeclaration { get; set; }
        public virtual ICollection<RuleDefinition> RuleDefinition { get; set; }
        public virtual ICollection<Match> Match { get; set; }
    }
}
