//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAnalyzer.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRole = new HashSet<UserRole>();
            this.MyProjects = new HashSet<ProjectDefinition>();
            this.MyContributionProjects = new HashSet<ProjectDefinition>();
            this.MyReadOnlyProjects = new HashSet<ProjectDefinition>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<ProjectDefinition> MyProjects { get; set; }
        public virtual ICollection<ProjectDefinition> MyContributionProjects { get; set; }
        public virtual ICollection<ProjectDefinition> MyReadOnlyProjects { get; set; }
    }
}
